### ISSUE TITLE
[QUESTION] - Migragate or start from scratch?

### ISSUE THREAD

**Issue by tramhao** [veeso/tui-realm#20]
Which is faster from your estimation? Thanks.

**Comment by veeso** [comment]
I think migrating is anyway faster. The update function stays quiete the same, except for the signature. You just change the current matching on key events with the `Msg` you define. The function where you render the ui with `draw()` stays the same, except that you use the `Application` instead of the `View`. Then all the places where you're using the old props builder you need to construct the `Component` you've defined for each element in your Ui.

The not so easy thing is to handle the fact that the ui model cannot handle the `Application`, so you may need a wrapper around these two. You can take [tuifeed](https://github.com/veeso/tuifeed) as a reference.

I'm my opinion migrating is not hard, it just takes relatively a long time and it's kinda boring, but I hope satisfying at the end.

**Comment by tramhao** [comment]
Thanks！

**Comment by tramhao** [comment]
And this is no longer used?
```
pub trait Activity {
    /// ### `on_create`
    ///
    /// `on_create` is the function which must be called to initialize the activity.
    /// `on_create` must initialize all the data structures used by the activity
    /// Context is taken from activity manager and will be released only when activity is destroyed
    fn on_create(&mut self, context: Context);

    /// ### `on_draw`
    ///
    /// `on_draw` is the function which draws the graphical interface.
    /// This function must be called at each tick to refresh the interface
    fn on_draw(&mut self);

    /// ### `will_umount`
    ///
    /// `will_umount` is the method which must be able to report to the activity manager, whether
    /// the activity should be terminated or not.
    /// If not, the call will return `None`, otherwise return`Some(ExitReason)`
    fn will_umount(&self) -> Option<&ExitReason>;

    /// ### `on_destroy`
    ///
    /// `on_destroy` is the function which cleans up runtime variables and data before terminating
    /// the activity. This function must be called once before terminating the activity.
    /// This function finally releases the context
    fn on_destroy(&mut self) -> Option<Context>;
}
```

**Comment by tramhao** [comment]
I tried to migrate but seems the whole structure changed. Probably I'll start from the example and add my stuff back gradually. Thanks.

**Comment by veeso** [comment]
The Activity trait is something I use in termscp in order to have different "Ui applications" and to handle their lifecycle easily in the main loop, but it's not related to tui-realm (the activity existed before tui-realm was implemented).
In my migration I'll keep activities, but I will make the struct implementing Activity to have a member `Model` which holds the UI model, the `Application` (which is the tui-realm application) and the `Context` (which holds data shared between activities).

**Comment by tramhao** [comment]
Thanks for the explanation. I always thought activity is a part of tui-realm but I was wrong.
