### ISSUE TITLE
[QUESTION] - How to send event to a component?

### ISSUE THREAD

**Issue by tramhao** [veeso/tui-realm#25]
Before migrating, I have below code:
```
// this is to keep the state of library
            let event: Event = Event::Key(KeyEvent {
                code: KeyCode::Down,
                modifiers: KeyModifiers::NONE,
            });
            self.view.on(event);
```
This code is specially used when delete an item from tree. After migrating, I can generate the same event as below:
```
let e: Event<NoUserEvent> = Event::Keyboard(KeyEvent {
                code: Key::Down,
                modifiers: KeyModifiers::NONE,
            });

```
But as there is no view, how should I send this message? Thanks.

**Comment by veeso** [comment]
There are other ways to get around the problem, but none of them injecting events this way. This is no more possible by design, since it's not the way it should be done in my mind.

1. If you're remounting the tree at erach update, the new `TreeView` component allows you to provide the initial node, so you can always create a function which calculates the new node when deleting one (basically [Orange trees](https://github.com/veeso/orange-trees) already provides all the methods you need to do so).
2. If you're using the `Update` to get the new tree, you can access to the states, as described here <https://github.com/veeso/tui-realm-treeview>
3. The dirty way: you can create a `Port` which has a member of type `Arc<RwLock<Option<Event>>>` that you can write from your application whenever you need to inject an event. In this case, it should be better to use Custom events (so, instead of `NoUserEvent` you'll have your events) and subscribe the tree to that kind of event, in order to perform the same task.

    ```rust
    pub struct EventInjector {
      ev_jar: Arc<RwLock<Event<MyUserEvent>>>>,
    }

    impl Poll<MyUserEvent> for EventInjector {
     ...
    }

    ```

**Comment by tramhao** [comment]
Thanks for pointing me to the right direction.
I finally work option 1 out like this:
```
                // // this is to keep the state of playlist
                self.reload_tree();
                let tree = self.tree.clone();
                if let Some(new_node) = tree.root().node_by_route(&route) {
                    self.sync_library(Some(new_node.id()));
                } else {
                    //special case 1: old route not available but have siblings
                    if let Some(last) = route.last_mut() {
                        if last > &mut 0 {
                            *last -= 1;
                        }
                    }
                    if let Some(new_node) = tree.root().node_by_route(&route) {
                        self.sync_library(Some(new_node.id()));
                    } else {
                        //special case 2: old route not available and no siblings
                        route.truncate(route.len() - 1);
                        if let Some(new_node) = tree.root().node_by_route(&route) {
                            self.sync_library(Some(new_node.id()));
                        }
                    }
                }

```
