### ISSUE TITLE
[Feature Request] - Treeview

### ISSUE THREAD

**Issue by tramhao** [veeso/tui-realm#7]
## Description

A treeview widget is very good to display a file tree.

### Changes

Perhaps a new component.

## Implementation

https://github.com/rivo/tview/blob/master/treeview.go

**Comment by veeso** [comment]
This is the first time someone asks for a new component, so I decided to take this as a good chance to define guidelines for new component candidates.
I don' think this would be a good candidate for a standard component, due to:

- too specific, not general purpose

but I've also added a new chapter in the readme for community components, which might be the right place for this component. I've seen someone has developed a [treeview widget](https://github.com/EdJoPaTo/tui-rs-tree-widget) for tui, which could be implemented as a realm component.

As soon as I have some spare time, I will implement a crate for this 😉

**Comment by tramhao** [comment]
Thanks for the quick response and will keep tracking this repo and your implementation. Hope I could learn fast enough to do similar thing. Thanks.

**Comment by veeso** [comment]
You're welcome. I've already initialized the repository: <https://github.com/veeso/tui-realm-treeview>

**Comment by veeso** [comment]
tui-realm-treeview has just been released
